# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ys, fishy, avit pygmalion
ZSH_THEME="fino"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    docker
    git
    sudo
    z
    zsh-autosuggestions
    zsh-completions
    zsh-syntax-highlighting
)

# User configuration
export PATH=$HOME/bin:/usr/local/bin:$PATH
export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# ============================== Custom =====================================
# for Language
# export LANG=en_US.UTF-8

# for MacOS
osType="Linux"
if [[ "$(uname -s)" == "Darwin" ]]; then
    osType="Darwin"
    export HOMEBREW_BOTTLE_DOMAIN='https://mirrors.aliyun.com/homebrew/homebrew-bottles'
fi

# for Java
# export JAVA_HOME=/usr/lib/jvm/java-8-sun
# export JRE_HOME=${JAVA_HOME}/jre
# export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
# export PATH=${JAVA_HOME}/bin:$PATH

# for Clipboard
alias pbcopy='xclip -selection c '
alias pbpast='xclip -selection c -o '


# for Debian
DEBMAIL="neeyongliang@gmail.com"
DEBFULLNAME="yongliang"

# for Terminal
# export https_proxy=http://127.0.0.1:9999
# export http_proxy=http://127.0.0.1:9999
# export all_proxy=socks5://127.0.0.1:9999

# for Alias
sendToMe() {
    scp -r $1 $USER@$HOST:~
}

cloneToMe() {
    echo "Will clone from git@${1:-github}.com:neeyongliang/${2:-test}.git"
    git clone git@${1:-github}.com:neeyongliang/${2:-test}.git
}

cloneToMe() {
    echo "Will clone from git@${1:-github}.com:neeyongliang/${2:-test}.git"
    git clone git@${1:-github}.com:neeyongliang/${2:-test}.git
}

cloneToMeHttp() {
    echo "Will clone from https://${1:-github}.com/neeyongliang/${2:-test}.git"
    git clone https://${1:-github}.com/neeyongliang/${2:-test}.git
}

alias stm=sendToMe $1
alias ctm=cloneToMe $1 $2
alias ctmh=cloneToMeHttp $1 $2

# =========================== Custom end ===================================
